name: Build binaries

on:
  schedule:
    - cron: "0 3 */2 * *"
  push:
  pull_request:
    paths:
    - '.github/workflows/*.yml'
    - './scripts/*.sh'
    - './rp2/*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout builder
        uses: actions/checkout@v1

      - name: Install arm toolchain
        run: ./scripts/install_arm.sh

      - name: Checkout ulab/micropython
        run: ./scripts/init.sh

      - name: Create artifacts directory
        run: mkdir ./artifacts

      - name: Add firmware files to rp2/modules
        run: cp -r ./rp2/* ./path/to/micropython/ports/rp2/modules/

      - name: Compile for raspberry pico
        if: always()
        run: ./scripts/rp2/pico.sh

      - name: Move firmware to artifacts
        run: mv ./repos/micropython/ports/rp2/build/*.uf2 ./artifacts/

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-firmware
          path: ./artifacts/

